id: I45564C16
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:28:45+00:00'
last_modified: '2022-06-09T06:55:59.305878+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16803
  title: ཙ་རི་སྨན་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '9955':
      image_group_id: I1KG17037
      title: Volume 1 of tsa ri sman rdzong /
      total_pages: 604
      order: 1
      base_file: 9955.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
