id: opecha:P007876
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16803
  title: ཙ་རི་སྨན་རྫོང་།
  volume:
    9a5d6ed318a34271a5da7320bdd162db:
      image_group_id: I1KG17037
      title: Volume 1 of tsa ri sman rdzong /
      volume_number: 1
      total_pages: 604
  author: ''
ebook_metadata:
  title: ཙ་རི་སྨན་རྫོང་།
  author: ''
  sku: P007876
  cover: cover.jpg
  layers:
  - pagination
