id: P007876
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:41.288914
source_metadata:
  id: bdr:W1KG16803
  title: ཙ་རི་སྨན་རྫོང་།
  author: ''
  volumes:
    9a5d6ed318a34271a5da7320bdd162db:
      image_group_id: I1KG17037
      title: Volume 1 of tsa ri sman rdzong /
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
