id: P007876
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16803
  title: ཙ་རི་སྨན་རྫོང་།
  author: ''
  volumes:
    bb5d4dbc91e34f4bba08f78634865560:
      image_group_id: I1KG17037
      title: ''
      volume_number: 1
      total_pages: 604
ebook_metadata:
  title: ཙ་རི་སྨན་རྫོང་།
  author: ''
  sku: P007876
  cover: cover.jpg
  layers:
  - pagination
